export const intentToKBCategory = {
  COUNTRY_SELECTION: "COUNTRY",
  COURSE_SELECTION: "COURSE",
  FEES_QUERY: "FEES",
  VISA_QUERY: "VISA",
  TEST_REQUIREMENT: "TEST",
  INTAKE_QUERY: "INTAKE",
  ELIGIBILITY_CHECK: "GENERAL",
};
